export enum AuthProvider {
  ARSNOVA = 'ARSNOVA',
  ARSNOVA_GUEST = 'ARSNOVA_GUEST',
  LDAP = 'LDAP',
  SAML = 'SAML',
  CAS = 'CAS',
  GOOGLE = 'GOOGLE',
  FACEBOOK = 'FACEBOOK',
  TWITTER = 'TWITTER',
}
