export enum ContentType {
  CHOICE = 'CHOICE',
  SCALE = 'SCALE',
  BINARY = 'BINARY',
  TEXT = 'TEXT',
  WORDCLOUD = 'WORDCLOUD',
  SORT = 'SORT',
  PRIORIZATION = 'PRIORIZATION',
  SLIDE = 'SLIDE',
  FLASHCARD = 'FLASHCARD'
}
