enableGlobalCache: true
nodeLinker: pnp

packageExtensions:
  '@angular-eslint/eslint-plugin-template@*':
    dependencies:
      '@typescript-eslint/types': '*'
  '@nx/devkit@*':
    dependencies:
      '@angular-devkit/architect': '~20.3.0'
  '@stomp/rx-stomp@*':
    dependencies:
      uuid: '^9.0.0'
  '@storybook/angular@*':
    dependencies:
      '@angular-devkit/build-angular': '~20.3.0'
      '@angular-devkit/architect': '~0.2003.0'
      '@angular-devkit/core': '~20.3.0'
  postcss-scss@*:
    dependencies:
      postcss: '*'
  storybook@*:
    dependencies:
      '@types/react': '*'
  webpack@*:
    dependencies:
      '@types/json-schema': '*'
