enableGlobalCache: true
enableScripts: false
nodeLinker: pnp
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@angular/*'
  - 'ng-packagr'
  - 'typescript'

packageExtensions:
  '@analogjs/storybook-angular@*':
    dependencies:
      '@analogjs/vite-plugin-angular': '*'
  '@stomp/rx-stomp@*':
    dependencies:
      uuid: '^9.0.0'
  '@storybook/angular@*':
    dependencies:
      '@angular-devkit/architect': '*'
      '@angular-devkit/core': '*'
  postcss-scss@*:
    dependencies:
      postcss: '*'
