enableGlobalCache: true
nodeLinker: pnp

packageExtensions:
  '@angular-eslint/eslint-plugin-template@*':
    dependencies:
      '@typescript-eslint/types': '*'
  '@nx/devkit@*':
    dependencies:
      '@angular-devkit/architect': '*'
  '@stomp/rx-stomp@*':
    dependencies:
      uuid: '^9.0.0'
  '@storybook/angular@*':
    dependencies:
      '@angular-devkit/architect': '*'
      '@angular-devkit/core': '*'
  '@storybook/core@*':
    dependencies:
      '@types/react': '*'
  postcss-scss@*:
    dependencies:
      postcss: '*'
