enableGlobalCache: true
nodeLinker: pnp

packageExtensions:
  '@angular/build@*':
    dependencies:
      'jsonc-parser': '*'
      'tslib': '*'
  '@angular-eslint/eslint-plugin-template@*':
    dependencies:
      '@typescript-eslint/types': '*'
  '@apollo/client@*':
    dependencies:
      '@types/react': '*'
  '@nx/devkit@*':
    dependencies:
      '@angular-devkit/architect': '*'
  '@stomp/rx-stomp@*':
    dependencies:
      uuid: '^9.0.0'
  '@storybook/angular@*':
    dependencies:
      '@angular-devkit/build-angular': '*'
      '@angular-devkit/architect': '*'
      '@angular-devkit/core': '*'
  postcss-scss@*:
    dependencies:
      postcss: '*'
  storybook@*:
    dependencies:
      '@types/react': '*'
  webpack@*:
    dependencies:
      '@types/json-schema': '*'
