enableGlobalCache: true
enableScripts: false
nodeLinker: pnp
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@schematics/angular'
  - 'ng-packagr'
  - 'typescript'
