export enum ContentType {
  CHOICE = 'CHOICE',
  TEXT = 'TEXT',
  SCALE = 'SCALE',
  WORDCLOUD = 'WORDCLOUD',
  BINARY = 'BINARY',
  NUMERIC = 'NUMERIC',
  SORT = 'SORT',
  SHORT_ANSWER = 'SHORT_ANSWER',
  PRIORITIZATION = 'PRIORITIZATION',
  SLIDE = 'SLIDE',
  FLASHCARD = 'FLASHCARD',
}
